### ISSUE TITLE
Error: Cannot find module 'esbuild'

### ISSUE THREAD

**Issue by laststandjam** [kontent-ai/integration-example-algolia#11]
### Brief bug description

Failing to install esbuild and to find package "@netlify/esbuild-windows-64" on the file system. Deployments to Netlify via Quick Deploy are failing for similar reason.

### Repro steps

1. Download Local Clone 
2. Run npm Install

Alternatively
 
1. Use "Deploy to Netlify" Button

### Expected behavior

Deploy to Netlify via quick deploy. 

### Additional context
Deploy Log

9:45:02 AM: build-image version: 5ad27658ebdf9c1e4379d77be303c2a3e3daa7bf (focal)
9:45:02 AM: buildbot version: 5ad27658ebdf9c1e4379d77be303c2a3e3daa7bf
9:45:02 AM: Fetching cached dependencies
9:45:02 AM: Failed to fetch cache, continuing with build
9:45:02 AM: Starting to prepare the repo for build
9:45:02 AM: No cached dependencies found. Cloning fresh repo
9:45:02 AM: git clone --filter=blob:none https://github.com/kontent-ai/integration-example-algolia
9:45:03 AM: Preparing Git Reference refs/heads/main
9:45:04 AM: Parsing package.json dependencies
9:45:05 AM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus '/build' in the Netlify UI
9:45:05 AM: Starting build script
9:45:05 AM: Installing dependencies
9:45:05 AM: Python version set to 2.7
9:45:05 AM: v16.19.1 is already installed.
9:45:06 AM: Now using node v16.19.1 (npm v8.19.3)
9:45:06 AM: Enabling Node.js Corepack
9:45:06 AM: Started restoring cached build plugins
9:45:06 AM: Finished restoring cached build plugins
9:45:06 AM: Attempting Ruby version 2.7.2, read from environment
9:45:06 AM: Using Ruby version 2.7.2
9:45:07 AM: Using PHP version 8.0
9:45:07 AM: Started restoring cached corepack dependencies
9:45:07 AM: Finished restoring cached corepack dependencies
9:45:07 AM: No npm workspaces detected
9:45:07 AM: Started restoring cached node modules
9:45:07 AM: Finished restoring cached node modules
9:45:07 AM: Installing npm packages using npm version 8.19.3
9:45:44 AM: npm ERR! code 1
9:45:44 AM: npm ERR! path /opt/build/repo/node_modules/netlify-cli/node_modules/@netlify/esbuild
9:45:44 AM: npm ERR! command failed
9:45:44 AM: npm ERR! command sh -c -- node install.js
9:45:44 AM: npm ERR! [esbuild] Failed to find package "@netlify/esbuild-linux-64" on the file system
9:45:44 AM: npm ERR!
9:45:44 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1 (https://ntl.fyi/exit-code-1)
9:45:44 AM: npm ERR! This can happen if you use the "--no-optional" flag. The "optionalDependencies"
9:45:44 AM: npm ERR! package.json feature is used by esbuild to install the correct binary executable
9:45:44 AM: npm ERR! for your current platform. This install script will now attempt to work around
9:45:44 AM: npm ERR! this. If that fails, you need to remove the "--no-optional" flag to use esbuild.
9:45:44 AM: npm ERR!
9:45:44 AM: npm ERR! node:internal/modules/cjs/loader:1021
9:45:44 AM: npm ERR!   const err = new Error(message);
9:45:44 AM: npm ERR!               ^
9:45:44 AM: npm ERR!
9:45:44 AM: npm ERR! Error: Cannot find module 'esbuild'
9:45:44 AM: npm ERR! Require stack:
9:45:44 AM: npm ERR! - /opt/build/repo/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js
9:45:44 AM: npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
9:45:44 AM: npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:114:19)
9:45:44 AM: npm ERR!     at downloadedBinPath (/opt/build/repo/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:86:46)
9:45:44 AM: npm ERR!     at checkAndPreparePackage (/opt/build/repo/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:232:15)
9:45:44 AM: npm ERR!     at Object.<anonymous> (/opt/build/repo/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js:247:1)
9:45:44 AM: npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1191:14)
9:45:44 AM: npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
9:45:44 AM: npm ERR!     at Module.load (node:internal/modules/cjs/loader:1069:32)
9:45:44 AM: npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
9:45:44 AM: npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
9:45:44 AM: npm ERR!   code: 'MODULE_NOT_FOUND',
9:45:44 AM: npm ERR!   requireStack: [
9:45:44 AM: npm ERR!     '/opt/build/repo/node_modules/netlify-cli/node_modules/@netlify/esbuild/install.js'
9:45:44 AM: npm ERR!   ]
9:45:44 AM: npm ERR! }
9:45:44 AM: npm ERR! A complete log of this run can be found in:
9:45:44 AM: npm ERR!     /opt/buildhome/.npm/_logs/2023-02-28T17_45_07_535Z-debug-0.log
9:45:44 AM: Error during npm install
9:45:44 AM: Build was terminated: Build script returned non-zero exit code: 1
9:45:44 AM: Failing build: Failed to build site
9:45:45 AM: Finished processing build request in 43.338s

**Comment by Simply007** [comment]
I [fixed the CI triggers](922fc8f4755b6a87f1b5c900fe9f2c4bdc92a2db) - and I can confirm reprodution https://github.com/kontent-ai/integration-example-algolia/actions/runs/4300771736/jobs/7497290554
