### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by laststandjam** [kontent-ai/integration-example-algolia#17]
### Brief bug description

Have set up the config in Kontent.ai as specified in the readme, but the custom element throws " Invalid element config, the following properties are missing or invalid 0, 1, 2, 3, 4, 5."

### Repro steps

1. Set up Custom Element via Quick Deploy
2. Set up custom element configuration in Kontent.ai 
3. Open the Item with the custom Element in Kontent.ai 

### Expected behavior

Validate element.config if correct, or point out specifically what properties of the config are invalid. 

### Additional context

config used {
    "language": "es-us",
    "projectId": "f9b63f57-16fd-0094-e757-2f72d2321c5f",
    "algoliaAppId": "VG5LKCBKWQ",
    "algoliaSearchKey": "ae3750d4df514f9bf3410909ed4d81c2",
    "algoliaIndexName": "Final_Test",
    "slugCodename": "url_slug"
}

### Screenshots

<img width="958" alt="image" src="https://github.com/kontent-ai/integration-example-algolia/assets/53449817/f9cebbce-f4c2-44a1-bc0b-5c39330e6686">

**Comment by JiriLojda** [comment]
Thank you for reporting the issue, I will have a look at it in the coming days.

**Comment by JiriLojda** [comment]
@laststandjam I tried to replicate the error, but I was not able to replicate the problem, even with the provided config. Can you please try again and provide me with a reproduction (e.g. invite me to a project with the problematic custom element) so I can see the error in action? I can't find anything in the code that could lead to the error you experienced.

**Comment by JiriLojda** [comment]
Hi @laststandjam, sorry for closing the issue, it got closed automatically. It appears there indeed was a bug in the logic that checked the provided configuration. I just merged a change that should fix this. Can you please check that the fix works for you? Then we can close this.

**Comment by laststandjam** [comment]
Fixed it! Thank you.
