### ISSUE TITLE
Multiple indexes in Algolia

### ISSUE THREAD

**Issue by akiselka-flexcon** [kontent-ai/integration-example-algolia#19]
### Motivation

Nicholas from Kontent.ai support suggested I submit a feature request. 

### Proposed solution

The feature request is to sync content from one Kontnet.ai site to more than one Algolia index. We want to have the same data in two different indexes in Algolia. One index would be for development (sandbox) and the other index would be for production.

**Comment by JiriLojda** [comment]
Hi @akiselka-flexcon,

Thank you for your interest in our Algolia integration. First I'd like to point out that the integration is meant as an example. We expect that every client has different needs and as such will adjust the example code to their needs as necessary.
From a quick look, I can see multiple ways to implement what you need.
1) If both of your indexes are accessible using the same Algolia API key, you can just create two webhooks with different index names in the URL.  As you can see [here](https://github.com/kontent-ai/integration-example-algolia/blob/aa9c3f9dd68b574aa76339866a1da94374cc9ebc/src/functions/algolia-update-webhook.ts#L48), the index name is specified in the query parameters and only the Algolia API key is from environment variables.
2) If you have your indexes under different Algolia API keys, you can still use the previous approach. You would just need to have two deployments of the code each with a different API key in the environment variables.
3) You can adjust [the code](https://github.com/kontent-ai/integration-example-algolia/blob/aa9c3f9dd68b574aa76339866a1da94374cc9ebc/src/functions/algolia-update-webhook.ts#L47) to accept another environment variable (something like `DEVELOPMENT_ALGOLIA_API_KEY`) and another set of query parameters (something like `developmentAppId` and `developmentIndex`, alternatively you can accept those values from environment variables as well if you prefer, the change in implementation is trivial). Then you would create two clients [here](https://github.com/kontent-ai/integration-example-algolia/blob/aa9c3f9dd68b574aa76339866a1da94374cc9ebc/src/functions/algolia-update-webhook.ts#L47) and [two index objects](https://github.com/kontent-ai/integration-example-algolia/blob/aa9c3f9dd68b574aa76339866a1da94374cc9ebc/src/functions/algolia-update-webhook.ts#L48). Then you would just duplicate all the usages of the index object to sync into both (I suggest putting all the operations into a function and calling it twice with different a index). With this approach, you would have just one webhook and one deployment.

I am not convinced that this is something we should add to the example itself as the current example can be easily adjusted to work in this case or it can even work without any adjustments to the code (as described above). We want to keep it reasonably simple to make it easy to adjust for specific needs.

Does one of the solutions work for you? Do you have a different approach in mind? Please, let me know so I can help you further or close the issue if you are satisfied with the options I presented.

**Comment by akiselka-flexcon** [comment]
Thanks for the info. I'll close this out.
